// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/go-kratos/kratos/v3"
	"github.com/go-kratos/kratos/v3/config"
	"github.com/google/wire"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"micro-one-api/api/billing/v1"
	"micro-one-api/api/channel/v1"
	"micro-one-api/api/identity/v1"
	"micro-one-api/api/log/v1"
	biz2 "micro-one-api/domain/subscription/biz"
	data2 "micro-one-api/domain/subscription/data"
	"micro-one-api/domain/upstream/credential"
	"micro-one-api/domain/upstream/provider"
	"micro-one-api/internal/adaptor"
	"micro-one-api/internal/biz"
	"micro-one-api/internal/data"
	"micro-one-api/internal/identity"
	"micro-one-api/internal/server"
	"micro-one-api/internal/service"
	"micro-one-api/pkg/timeout"
	"micro-one-api/platform/audit"
	"micro-one-api/platform/cache"
	"micro-one-api/platform/config"
	"micro-one-api/platform/database/xdb"
	"micro-one-api/platform/events"
	grpc2 "micro-one-api/platform/grpc"
	"micro-one-api/platform/logging"
	"micro-one-api/platform/metrics"
	"micro-one-api/platform/middleware"
	"micro-one-api/platform/registry"
	"micro-one-api/platform/security/auth"
	"micro-one-api/platform/tls"
	"net/http"
	"os"
	"time"
)

// Injectors from wire.go:

func InitApp(confPath string) (*kratos.App, func(), error) {
	config, err := loadConfig(confPath)
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := newApp(config)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet declares the relay-gateway providers. loadConfig lives in
// config_loader.go and the helper functions (newModelMapper, newRetryPolicy,
// createAuthenticatedClient, etc.) live in relay_helpers.go so they are
// visible under both build tags.
//
// relay-gateway's wiring is more complex than the other services (conditional
// client construction, environment-variable-driven configuration, etc.), so
// newApp constructs the provider factory, relay usecase, and HTTP server
// internally rather than declaring them as separate Wire providers.
var ProviderSet = wire.NewSet(
	loadConfig,
	newApp,
)

func newApp(cfg *Config) (*kratos.App, func(), error) {
	tlsConfig := tls.LoadTLSConfig()
	enableAuth := os.Getenv("ENABLE_AUTH") != "false"
	var serviceAuth *auth.ServiceAuthConfig
	if enableAuth {
		var err error
		serviceAuth, err = auth.LoadServiceAuthConfig()
		if err != nil {
			return nil, nil, fmt.Errorf("load service auth config: %w", err)
		}
	}

	providerTimeout := timeout.GetUpstreamTimeout()
	if timeoutStr := os.Getenv("RELAY_PROVIDER_TIMEOUT"); timeoutStr != "" {
		if duration, err := time.ParseDuration(timeoutStr); err == nil {
			providerTimeout = duration
		}
	}

	discovery, err := registry.NewDiscovery(cfg.Registry())
	if err != nil {
		return nil, nil, fmt.Errorf("create discovery: %w", err)
	}
	registrar, err := registry.NewRegistrar(cfg.Registry())
	if err != nil {
		return nil, nil, fmt.Errorf("create registrar: %w", err)
	}

	resolver := registry.NewResolver(discovery)
	resolver.SetStatic("identity-service", cfg.Bootstrap.Clients.Identity.Endpoint)
	resolver.SetStatic("channel-service", cfg.Bootstrap.Clients.Channel.Endpoint)
	resolver.SetStatic("billing-service", cfg.Bootstrap.Clients.Billing.Endpoint)
	resolver.SetStatic("log-service", cfg.Bootstrap.Clients.Log.Endpoint)

	var identityConn, channelConn, billingConn, logConn *grpc.ClientConn
	var identityClient identityv1.IdentityServiceClient
	var channelClient channelv1.ChannelServiceClient
	var billingClient billingv1.BillingServiceClient
	var logClient logv1.LogServiceClient

	identityEndpoint, err := resolver.ResolveGRPC(context.Background(), "identity-service")
	if err != nil {
		return nil, nil, fmt.Errorf("resolve identity-service endpoint: %w", err)
	}
	channelEndpoint, err := resolver.ResolveGRPC(context.Background(), "channel-service")
	if err != nil {
		return nil, nil, fmt.Errorf("resolve channel-service endpoint: %w", err)
	}
	billingEndpoint, err := resolver.ResolveGRPC(context.Background(), "billing-service")
	if err != nil {
		return nil, nil, fmt.Errorf("resolve billing-service endpoint: %w", err)
	}
	logEndpoint, err := resolver.ResolveGRPC(context.Background(), "log-service")
	if err != nil {
		return nil, nil, fmt.Errorf("resolve log-service endpoint: %w", err)
	}

	if enableAuth && tlsConfig.Enabled {
		identityConn, err = createAuthenticatedClient(identityEndpoint, tlsConfig, serviceAuth)
		if err != nil {
			return nil, nil, fmt.Errorf("create identity gRPC client: %w", err)
		}
		channelConn, err = createAuthenticatedClient(channelEndpoint, tlsConfig, serviceAuth)
		if err != nil {
			return nil, nil, fmt.Errorf("create channel gRPC client: %w", err)
		}
		billingConn, err = createAuthenticatedClient(billingEndpoint, tlsConfig, serviceAuth)
		if err != nil {
			return nil, nil, fmt.Errorf("create billing gRPC client: %w", err)
		}
		logConn, err = createAuthenticatedClient(logEndpoint, tlsConfig, serviceAuth)
		if err != nil {
			return nil, nil, fmt.Errorf("create log gRPC client: %w", err)
		}
	} else {
		identityConn, err = grpc.NewClient(identityEndpoint, grpc.WithTransportCredentials(insecure.NewCredentials()))
		if err != nil {
			return nil, nil, fmt.Errorf("create identity gRPC client: %w", err)
		}
		channelConn, err = grpc.NewClient(channelEndpoint, grpc.WithTransportCredentials(insecure.NewCredentials()))
		if err != nil {
			return nil, nil, fmt.Errorf("create channel gRPC client: %w", err)
		}
		billingConn, err = grpc.NewClient(billingEndpoint, grpc.WithTransportCredentials(insecure.NewCredentials()))
		if err != nil {
			return nil, nil, fmt.Errorf("create billing gRPC client: %w", err)
		}
		logConn, err = grpc.NewClient(logEndpoint, grpc.WithTransportCredentials(insecure.NewCredentials()))
		if err != nil {
			return nil, nil, fmt.Errorf("create log gRPC client: %w", err)
		}
	}

	identityClient = identityv1.NewIdentityServiceClient(identityConn)
	channelClient = channelv1.NewChannelServiceClient(channelConn)
	billingClient = billingv1.NewBillingServiceClient(billingConn)
	logClient = logv1.NewLogServiceClient(logConn)

	resilienceTimeout := parseDurationOrDefault(cfg.Bootstrap.Resilience.Timeout, 3*time.Second)
	if cfg.Bootstrap.Resilience.Enabled {
		identityClient = data.NewResilientIdentityClient(identityClient, resilienceTimeout)
		channelClient = data.NewResilientChannelClient(channelClient, resilienceTimeout)
		billingClient = data.NewResilientBillingClient(billingClient, resilienceTimeout)
		logClient = data.NewResilientLogClient(logClient, resilienceTimeout)
	}

	providerFactory := provider.NewProviderFactory(providerTimeout)
	adaptor.SetProviderFactory(providerFactory)

	identityTTL := parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.GetIdentityTtl(), 24*time.Hour)
	identityService := identity.NewIdentityService(identityTTL)
	adaptor.SetIdentityService(identityService)

	accountLookup := data.NewChannelSubscriptionAccountStore(channelClient)
	claudeTokenProvider := credential.NewClaudeTokenProvider(accountLookup)
	codexTokenProvider := credential.NewOpenAITokenProvider(accountLookup)

	tokenFactory := func(platform identity.Platform) credential.TokenProvider {
		switch platform {
		case identity.PlatformClaude:
			return claudeTokenProvider
		case identity.PlatformCodex:
			return codexTokenProvider
		default:
			return nil
		}
	}
	adaptor.SetTokenProviderFactory(tokenFactory)

	accountResolver := accountLookup
	oauthHTTPClient := &http.Client{Timeout: providerTimeout}

	var refreshTask *credential.RefreshTask
	if cfg.Bootstrap.HybridAdaptor.GetTokenRefreshEnabled() {
		refreshTask = credential.NewRefreshTask(
			map[credential.Platform]credential.TokenProvider{credential.PlatformClaude: claudeTokenProvider, credential.PlatformCodex: codexTokenProvider},
			accountLookup,
			func(accountID int64) credential.Platform {
				return accountLookup.PlatformOf(context.Background(), accountID)
			}, credential.RefreshTaskConfig{
				Interval:                  parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.GetRefreshInterval(), 10*time.Minute),
				Lookahead:                 parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.GetRefreshLookahead(), 24*time.Hour),
				MaxRetries:                int(cfg.Bootstrap.HybridAdaptor.TokenRefresh.MaxRetries),
				RetryBackoff:              time.Duration(cfg.Bootstrap.HybridAdaptor.TokenRefresh.RetryBackoffSeconds) * time.Second,
				TempUnschedulableDuration: parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.TokenRefresh.TempUnschedDuration, 10*time.Minute),
				Hook:                      accountLookup,
			},
		)
		refreshTask.Start()
	}

	redisAddr := cfg.Bootstrap.Redis.Addr
	redisPassword := cfg.Bootstrap.Redis.Password
	if redisAddr == "" {
		redisAddr = cfg.Bootstrap.OpenaiWs.RedisAddr
		redisPassword = cfg.Bootstrap.OpenaiWs.RedisPassword
	}
	redisClient := xdb.NewRedisClient(redisAddr, redisPassword)
	eventBus := events.NewConfiguredEventBus(redisClient, "relay-gateway")
	authLoader := cache.NewAuthCacheLoader(identityClient, nil, resilienceTimeout)
	authCache, err := cache.NewAuthCache(redisClient, nil, authLoader.Load)
	if err != nil {
		return nil, nil, fmt.Errorf("create auth cache: %w", err)
	}
	identityClient = data.NewCachedIdentityClient(identityClient, authCache)

	if cfg.Bootstrap.ChannelCache.GetChannelCacheEnabled() {
		channelLoader := cache.NewChannelCacheLoader(channelClient, nil, resilienceTimeout)
		channelCache, err := cache.NewChannelCache(redisClient, nil, channelLoader.Load)
		if err != nil {
			return nil, nil, fmt.Errorf("create channel cache: %w", err)
		}
		channelClient = data.NewCachedChannelClient(channelClient, channelCache)
	}

	modelMapper := newModelMapper(cfg)
	var modelReloadStop func()
	if mm := modelMapper; mm != nil {

		if mp := modelsConfigPath(cfg); mp != "" {
			modelReloadStop, _ = xconfig.SubscribeFile(mp, func(_ *config.KeyValue) {
				if err := mm.Reload(); err != nil {
					logger.Log.
						Warn("models.yaml hot reload failed; keeping previous snapshot", zap.String("path", mp), zap.Error(err))
					return
				}
				logger.Log.
					Info("models.yaml hot-reloaded", zap.String("path", mp))
			})
		}
	}
	retryPolicy := newRetryPolicy(cfg)

	identityAdapter := data.NewIdentityAdapter(identityClient)
	channelAdapter := data.NewChannelAdapter(channelClient)
	relayUsecase := biz.NewRelayUsecase(identityAdapter, channelAdapter, modelMapper, retryPolicy)
	relayUsecase.SetRuntimeBlocker(biz.NewMemoryRuntimeBlocker())

	httpServer := server.NewHTTPServer(identityClient, channelClient, billingClient, providerFactory, relayUsecase, logClient)
	httpServer.SetHybridAdaptorEnabled(cfg.Bootstrap.HybridAdaptor.GetHybridAdaptorEnabled())
	httpServer.SetSubscriptionSessionStickyEnabled(cfg.Bootstrap.SessionSticky.GetSessionStickyEnabled())
	httpServer.SetRelayOrchestratorEnabled(cfg.Bootstrap.RelayOrchestrator.GetRelayOrchestratorEnabled())
	httpServer.SetSubscriptionAccountResolver(accountResolver)
	httpServer.SetOAuthHTTPClient(oauthHTTPClient)
	httpServer.SetSubscriptionAccountQuotaRecorder(accountLookup)
	httpServer.SetUserRPMLimit(cfg.Bootstrap.Subscription.GetUserRPMLimit())
	httpServer.SetRuntimeBlockDurations(
		parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.RuntimeBlock.GetRateLimitedDuration(), 5*time.Second),
		parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.RuntimeBlock.GetUnauthorizedDuration(), 2*time.Minute),
		parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.RuntimeBlock.GetServerErrorDuration(), 2*time.Minute),
		parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.RuntimeBlock.GetOverloadedDuration(), 30*time.Second),
	)
	stopBlockerReporter := func() {}
	if redisClient != nil {
		redisBlocker := biz.NewRedisRuntimeBlocker(redisClient)
		httpServer.SetRuntimeBlocker(redisBlocker)
		stopBlockerReporter = redisBlocker.StartActiveGaugeReporter(
			parseDurationOrDefault(cfg.Bootstrap.HybridAdaptor.RuntimeBlock.GetActiveGaugeInterval(), 30*time.Second),
			func(v float64) {
				metrics.RelayRuntimeBlockActive.Set(v)
			},
		)
		if redisLimiter := biz.NewRedisAccountConcurrencyLimiter(redisClient); redisLimiter != nil {
			httpServer.SetAccountConcurrencyLimiter(redisLimiter)
		}
		if redisRPMLimiter := biz.NewRedisAccountRPMLimiter(redisClient); redisRPMLimiter != nil {
			httpServer.SetAccountRPMLimiter(redisRPMLimiter)
		}
		if redisUserRPMLimiter := biz.NewRedisUserRPMLimiter(redisClient); redisUserRPMLimiter != nil {
			httpServer.SetUserRPMLimiter(redisUserRPMLimiter)
		}
	}

	var routeMiddleware []func(http.Handler) http.Handler
	if cfg.Bootstrap.Subscription.GetSubscriptionEnabled() {
		subscriptionRepo, subErr := data2.NewRepositoryFromEnv(os.Getenv("SQL_DRIVER"))
		if subErr != nil {
			return nil, nil, fmt.Errorf("create subscription repository: %w", subErr)
		}
		subscriptionUc := biz2.NewSubscriptionUsecase(subscriptionRepo, subscriptionRepo)
		httpServer.SetSubscriptionUsecase(subscriptionUc)
		routeMiddleware = append(routeMiddleware, httpServer.SubscriptionQuotaMiddleware)
	}
	if cfg.Bootstrap.Idempotency.Enabled {
		ttl := parseDurationOrDefault(cfg.Bootstrap.Idempotency.Ttl, 24*time.Hour)
		routeMiddleware = append(routeMiddleware, middleware.NewIdempotencyMiddleware(redisClient, &middleware.IdempotencyConfig{
			Header:    "Idempotency-Key",
			TTL:       ttl,
			CacheKeys: true,
		}).Handler)
	}
	if cfg.Bootstrap.Audit.Enabled {
		routeMiddleware = append(routeMiddleware, audit.NewMiddleware(audit.NewAuditor(true)).Handler)
	}
	httpServer.UseRouteMiddleware(routeMiddleware...)

	{

		wsWrite, _ := time.ParseDuration(cfg.Bootstrap.OpenaiWs.GetOpenAIWSWriteTimeout())
		wsIdle, _ := time.ParseDuration(cfg.Bootstrap.OpenaiWs.GetOpenAIWSIdleTimeout())
		wsDial, _ := time.ParseDuration(cfg.Bootstrap.OpenaiWs.GetOpenAIWSDialTimeout())
		wsFirst, _ := time.ParseDuration(cfg.Bootstrap.OpenaiWs.GetOpenAIWSFirstMessageTimeout())

		wsDrain, _ := time.ParseDuration(cfg.Bootstrap.OpenaiWs.GetOpenAIWSDrainTimeout())
		if wsDrain > 0 {
			httpServer.SetOpenAIWSDrainConfig(appwsDrainConfig(wsDrain))
		}
		httpServer.SetOpenAIWSTimeouts(wsWrite, wsIdle, wsDial, wsFirst)
		httpServer.SetOpenAIWSConnPool()
		httpServer.SetOpenAIWSPoolConfig(
			cfg.Bootstrap.OpenaiWs.GetOpenAIWSMaxConnsPerChannel(),
			cfg.Bootstrap.OpenaiWs.GetOpenAIWSFailoverMaxSwitches(),
			parseDurationOrDefault(cfg.Bootstrap.OpenaiWs.GetOpenAIWSStickyTTL(), time.Hour),
		)
		httpServer.SetOpenAIWSStickyStore(redisClient)
	}

	srv := newKratosHTTPServer(cfg, httpServer, providerTimeout)

	grpcSvc := service.NewRelayGrpcService(identityClient, channelClient, billingClient, providerFactory, relayUsecase)
	var relayGRPCOpts []grpc.ServerOption
	if cfg.Bootstrap.Mtls.Enabled {
		mtlsOpts, mtlsErr := grpc2.MTLSServerOptions(cfg.Bootstrap.Mtls.CertFile, cfg.Bootstrap.Mtls.KeyFile, cfg.Bootstrap.Mtls.CaFile)
		if mtlsErr != nil {
			return nil, nil, fmt.Errorf("create relay mTLS server options: %w", mtlsErr)
		}
		relayGRPCOpts = append(relayGRPCOpts, mtlsOpts...)
	}
	grpcSrv := server.NewGRPCServer(cfg.Bootstrap.Server.Grpc.Addr, grpcSvc, relayGRPCOpts...)

	drainTimeout := parseDurationOrDefault(cfg.Bootstrap.OpenaiWs.GetOpenAIWSDrainTimeout(), 30*time.Second)
	stopTimeout := drainTimeout + 10*time.Second

	kratosOpts := []kratos.Option{kratos.Name("relay-gateway"), kratos.Server(srv, grpcSrv), kratos.StopTimeout(stopTimeout), kratos.BeforeStop(func(ctx context.Context) error {
		drainCtx, cancel := context.WithTimeout(ctx, drainTimeout)
		defer cancel()
		_ = httpServer.DrainWSConnections(drainCtx)
		return nil
	}),
	}
	if registrar != nil {
		kratosOpts = append(kratosOpts, kratos.Registrar(registrar))
	}
	app := kratos.New(kratosOpts...)
	logger.Log.
		Info("relay-gateway starting", zap.String("http_addr", cfg.Bootstrap.Server.Http.Addr))

	cleanup := func() {
		if modelReloadStop != nil {
			modelReloadStop()
		}
		if refreshTask != nil {
			refreshTask.Stop()
		}
		stopBlockerReporter()
		if authCache != nil {
			_ = authCache.Close()
		}
		if closer, ok := eventBus.(interface{ Close() error }); ok {
			_ = closer.Close()
		}
		if redisClient != nil {
			_ = redisClient.Close()
		}
		identityConn.Close()
		channelConn.Close()
		billingConn.Close()
		logConn.Close()
	}

	return app, cleanup, nil
}
