// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/log/v1/log.proto

package logv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_api_log_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *GetLogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLogResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level            string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source           string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	RequestId        string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId           int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username         string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	TokenName        string                 `protobuf:"bytes,9,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	ModelName        string                 `protobuf:"bytes,10,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Quota            int64                  `protobuf:"varint,11,opt,name=quota,proto3" json:"quota,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,12,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,13,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ChannelId        int64                  `protobuf:"varint,14,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ElapsedTime      int64                  `protobuf:"varint,15,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	IsStream         bool                   `protobuf:"varint,16,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLogResponse) Reset() {
	*x = GetLogResponse{}
	mi := &file_api_log_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogResponse) ProtoMessage() {}

func (x *GetLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogResponse.ProtoReflect.Descriptor instead.
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *GetLogResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLogResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLogResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetLogResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetLogResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLogResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetLogResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetLogResponse) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *GetLogResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetLogResponse) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *GetLogResponse) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *GetLogResponse) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *GetLogResponse) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetLogResponse) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *GetLogResponse) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type ListLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsRequest) Reset() {
	*x = ListLogsRequest{}
	mi := &file_api_log_v1_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsRequest) ProtoMessage() {}

func (x *ListLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsRequest.ProtoReflect.Descriptor instead.
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLogsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetLogResponse      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsResponse) Reset() {
	*x = ListLogsResponse{}
	mi := &file_api_log_v1_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsResponse) ProtoMessage() {}

func (x *ListLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsResponse.ProtoReflect.Descriptor instead.
func (*ListLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{3}
}

func (x *ListLogsResponse) GetItems() []*GetLogResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IngestLogRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Level            string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Source           string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId           int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	TokenName        string                 `protobuf:"bytes,7,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	ModelName        string                 `protobuf:"bytes,8,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Quota            int64                  `protobuf:"varint,9,opt,name=quota,proto3" json:"quota,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,10,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,11,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ChannelId        int64                  `protobuf:"varint,12,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ElapsedTime      int64                  `protobuf:"varint,13,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	IsStream         bool                   `protobuf:"varint,14,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestLogRequest) Reset() {
	*x = IngestLogRequest{}
	mi := &file_api_log_v1_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogRequest) ProtoMessage() {}

func (x *IngestLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogRequest.ProtoReflect.Descriptor instead.
func (*IngestLogRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{4}
}

func (x *IngestLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *IngestLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestLogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IngestLogRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IngestLogRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IngestLogRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *IngestLogRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *IngestLogRequest) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *IngestLogRequest) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *IngestLogRequest) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *IngestLogRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *IngestLogRequest) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *IngestLogRequest) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type IngestLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogResponse) Reset() {
	*x = IngestLogResponse{}
	mi := &file_api_log_v1_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogResponse) ProtoMessage() {}

func (x *IngestLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogResponse.ProtoReflect.Descriptor instead.
func (*IngestLogResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_proto_rawDescGZIP(), []int{5}
}

func (x *IngestLogResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_log_v1_log_proto protoreflect.FileDescriptor

const file_api_log_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x14api/log/v1/log.proto\x12\n" +
	"api.log.v1\x1a\x1cgoogle/api/annotations.proto\"\x1f\n" +
	"\rGetLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe0\x03\n" +
	"\x0eGetLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"token_name\x18\t \x01(\tR\ttokenName\x12\x1d\n" +
	"\n" +
	"model_name\x18\n" +
	" \x01(\tR\tmodelName\x12\x14\n" +
	"\x05quota\x18\v \x01(\x03R\x05quota\x12#\n" +
	"\rprompt_tokens\x18\f \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\r \x01(\x03R\x10completionTokens\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x0e \x01(\x03R\tchannelId\x12!\n" +
	"\felapsed_time\x18\x0f \x01(\x03R\velapsedTime\x12\x1b\n" +
	"\tis_stream\x18\x10 \x01(\bR\bisStream\"V\n" +
	"\x0fListLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"Z\n" +
	"\x10ListLogsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.api.log.v1.GetLogResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb3\x03\n" +
	"\x10IngestLogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"token_name\x18\a \x01(\tR\ttokenName\x12\x1d\n" +
	"\n" +
	"model_name\x18\b \x01(\tR\tmodelName\x12\x14\n" +
	"\x05quota\x18\t \x01(\x03R\x05quota\x12#\n" +
	"\rprompt_tokens\x18\n" +
	" \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\v \x01(\x03R\x10completionTokens\x12\x1d\n" +
	"\n" +
	"channel_id\x18\f \x01(\x03R\tchannelId\x12!\n" +
	"\felapsed_time\x18\r \x01(\x03R\velapsedTime\x12\x1b\n" +
	"\tis_stream\x18\x0e \x01(\bR\bisStream\"#\n" +
	"\x11IngestLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\x9c\x02\n" +
	"\n" +
	"LogService\x12V\n" +
	"\x06GetLog\x12\x19.api.log.v1.GetLogRequest\x1a\x1a.api.log.v1.GetLogResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/logs/{id}\x12W\n" +
	"\bListLogs\x12\x1b.api.log.v1.ListLogsRequest\x1a\x1c.api.log.v1.ListLogsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/logs\x12]\n" +
	"\tIngestLog\x12\x1c.api.log.v1.IngestLogRequest\x1a\x1d.api.log.v1.IngestLogResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/logsB Z\x1emicro-one-api/api/log/v1;logv1b\x06proto3"

var (
	file_api_log_v1_log_proto_rawDescOnce sync.Once
	file_api_log_v1_log_proto_rawDescData []byte
)

func file_api_log_v1_log_proto_rawDescGZIP() []byte {
	file_api_log_v1_log_proto_rawDescOnce.Do(func() {
		file_api_log_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_log_v1_log_proto_rawDesc), len(file_api_log_v1_log_proto_rawDesc)))
	})
	return file_api_log_v1_log_proto_rawDescData
}

var file_api_log_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_log_v1_log_proto_goTypes = []any{
	(*GetLogRequest)(nil),     // 0: api.log.v1.GetLogRequest
	(*GetLogResponse)(nil),    // 1: api.log.v1.GetLogResponse
	(*ListLogsRequest)(nil),   // 2: api.log.v1.ListLogsRequest
	(*ListLogsResponse)(nil),  // 3: api.log.v1.ListLogsResponse
	(*IngestLogRequest)(nil),  // 4: api.log.v1.IngestLogRequest
	(*IngestLogResponse)(nil), // 5: api.log.v1.IngestLogResponse
}
var file_api_log_v1_log_proto_depIdxs = []int32{
	1, // 0: api.log.v1.ListLogsResponse.items:type_name -> api.log.v1.GetLogResponse
	0, // 1: api.log.v1.LogService.GetLog:input_type -> api.log.v1.GetLogRequest
	2, // 2: api.log.v1.LogService.ListLogs:input_type -> api.log.v1.ListLogsRequest
	4, // 3: api.log.v1.LogService.IngestLog:input_type -> api.log.v1.IngestLogRequest
	1, // 4: api.log.v1.LogService.GetLog:output_type -> api.log.v1.GetLogResponse
	3, // 5: api.log.v1.LogService.ListLogs:output_type -> api.log.v1.ListLogsResponse
	5, // 6: api.log.v1.LogService.IngestLog:output_type -> api.log.v1.IngestLogResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_log_v1_log_proto_init() }
func file_api_log_v1_log_proto_init() {
	if File_api_log_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_log_v1_log_proto_rawDesc), len(file_api_log_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_log_v1_log_proto_goTypes,
		DependencyIndexes: file_api_log_v1_log_proto_depIdxs,
		MessageInfos:      file_api_log_v1_log_proto_msgTypes,
	}.Build()
	File_api_log_v1_log_proto = out.File
	file_api_log_v1_log_proto_goTypes = nil
	file_api_log_v1_log_proto_depIdxs = nil
}
