// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration loaded from config.yaml.
type Bootstrap struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Server            *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Clients           *Clients               `protobuf:"bytes,2,opt,name=clients,proto3" json:"clients,omitempty"`
	Retry             *Retry                 `protobuf:"bytes,3,opt,name=retry,proto3" json:"retry,omitempty"`
	Models            *Models                `protobuf:"bytes,4,opt,name=models,proto3" json:"models,omitempty"`
	Registry          *Registry              `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	Redis             *Redis                 `protobuf:"bytes,6,opt,name=redis,proto3" json:"redis,omitempty"`
	OpenaiWs          *OpenaiWS              `protobuf:"bytes,7,opt,name=openai_ws,json=openaiWs,proto3" json:"openai_ws,omitempty"`
	HybridAdaptor     *HybridAdaptor         `protobuf:"bytes,8,opt,name=hybrid_adaptor,json=hybridAdaptor,proto3" json:"hybrid_adaptor,omitempty"`
	SessionSticky     *SessionSticky         `protobuf:"bytes,9,opt,name=session_sticky,json=sessionSticky,proto3" json:"session_sticky,omitempty"`
	Subscription      *Subscription          `protobuf:"bytes,10,opt,name=subscription,proto3" json:"subscription,omitempty"`
	RelayOrchestrator *RelayOrchestrator     `protobuf:"bytes,11,opt,name=relay_orchestrator,json=relayOrchestrator,proto3" json:"relay_orchestrator,omitempty"`
	ChannelCache      *ChannelCache          `protobuf:"bytes,12,opt,name=channel_cache,json=channelCache,proto3" json:"channel_cache,omitempty"`
	Idempotency       *Idempotency           `protobuf:"bytes,13,opt,name=idempotency,proto3" json:"idempotency,omitempty"`
	Audit             *Audit                 `protobuf:"bytes,14,opt,name=audit,proto3" json:"audit,omitempty"`
	Resilience        *Resilience            `protobuf:"bytes,15,opt,name=resilience,proto3" json:"resilience,omitempty"`
	Mtls              *Mtls                  `protobuf:"bytes,16,opt,name=mtls,proto3" json:"mtls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClients() *Clients {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Bootstrap) GetRetry() *Retry {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Bootstrap) GetModels() *Models {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Bootstrap) GetOpenaiWs() *OpenaiWS {
	if x != nil {
		return x.OpenaiWs
	}
	return nil
}

func (x *Bootstrap) GetHybridAdaptor() *HybridAdaptor {
	if x != nil {
		return x.HybridAdaptor
	}
	return nil
}

func (x *Bootstrap) GetSessionSticky() *SessionSticky {
	if x != nil {
		return x.SessionSticky
	}
	return nil
}

func (x *Bootstrap) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Bootstrap) GetRelayOrchestrator() *RelayOrchestrator {
	if x != nil {
		return x.RelayOrchestrator
	}
	return nil
}

func (x *Bootstrap) GetChannelCache() *ChannelCache {
	if x != nil {
		return x.ChannelCache
	}
	return nil
}

func (x *Bootstrap) GetIdempotency() *Idempotency {
	if x != nil {
		return x.Idempotency
	}
	return nil
}

func (x *Bootstrap) GetAudit() *Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *Bootstrap) GetResilience() *Resilience {
	if x != nil {
		return x.Resilience
	}
	return nil
}

func (x *Bootstrap) GetMtls() *Mtls {
	if x != nil {
		return x.Mtls
	}
	return nil
}

// Server holds the HTTP and gRPC server configuration.
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *HTTP                  `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *GRPC                  `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTP) Reset() {
	*x = HTTP{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTP) ProtoMessage() {}

func (x *HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTP.ProtoReflect.Descriptor instead.
func (*HTTP) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// Clients holds the client endpoint configuration.
type Clients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Channel       *Channel               `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Billing       *Billing               `protobuf:"bytes,3,opt,name=billing,proto3" json:"billing,omitempty"`
	Log           *Log                   `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clients) Reset() {
	*x = Clients{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clients) ProtoMessage() {}

func (x *Clients) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clients.ProtoReflect.Descriptor instead.
func (*Clients) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Clients) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Clients) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Clients) GetBilling() *Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

func (x *Clients) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Identity) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Channel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Billing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Billing) Reset() {
	*x = Billing{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Billing) ProtoMessage() {}

func (x *Billing) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Billing.ProtoReflect.Descriptor instead.
func (*Billing) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Billing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Log) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// Retry holds retry configuration for upstream provider calls.
type Retry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts     int32                  `protobuf:"varint,1,opt,name=max_attempts,proto3" json:"max_attempts,omitempty"`
	InitialInterval string                 `protobuf:"bytes,2,opt,name=initial_interval,proto3" json:"initial_interval,omitempty"`
	MaxInterval     string                 `protobuf:"bytes,3,opt,name=max_interval,proto3" json:"max_interval,omitempty"`
	Multiplier      float64                `protobuf:"fixed64,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	RetryableStatus []int32                `protobuf:"varint,5,rep,packed,name=retryable_status,proto3" json:"retryable_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Retry) Reset() {
	*x = Retry{}
	mi := &file_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retry) ProtoMessage() {}

func (x *Retry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retry.ProtoReflect.Descriptor instead.
func (*Retry) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Retry) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Retry) GetInitialInterval() string {
	if x != nil {
		return x.InitialInterval
	}
	return ""
}

func (x *Retry) GetMaxInterval() string {
	if x != nil {
		return x.MaxInterval
	}
	return ""
}

func (x *Retry) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *Retry) GetRetryableStatus() []int32 {
	if x != nil {
		return x.RetryableStatus
	}
	return nil
}

// ModelsConfig holds model mapping configuration.
type Models struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Models) Reset() {
	*x = Models{}
	mi := &file_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Models) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Models) ProtoMessage() {}

func (x *Models) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Models.ProtoReflect.Descriptor instead.
func (*Models) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Models) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// RedisConfig holds Redis configuration.
type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Registry holds the service registry configuration.
type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Consul        *Consul                `protobuf:"bytes,2,opt,name=consul,proto3" json:"consul,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{12}
}

func (x *Registry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Registry) GetConsul() *Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

func (x *Registry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Consul struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Address             string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	HealthCheckInterval int64                  `protobuf:"varint,2,opt,name=health_check_interval,proto3" json:"health_check_interval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Consul) Reset() {
	*x = Consul{}
	mi := &file_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consul) ProtoMessage() {}

func (x *Consul) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consul.ProtoReflect.Descriptor instead.
func (*Consul) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{13}
}

func (x *Consul) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Consul) GetHealthCheckInterval() int64 {
	if x != nil {
		return x.HealthCheckInterval
	}
	return 0
}

// OpenaiWSConfig holds tunables for the Codex Responses WebSocket relay.
type OpenaiWS struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WriteTimeout        string                 `protobuf:"bytes,1,opt,name=write_timeout,proto3" json:"write_timeout,omitempty"`
	IdleTimeout         string                 `protobuf:"bytes,2,opt,name=idle_timeout,proto3" json:"idle_timeout,omitempty"`
	DialTimeout         string                 `protobuf:"bytes,3,opt,name=dial_timeout,proto3" json:"dial_timeout,omitempty"`
	FirstMessageTimeout string                 `protobuf:"bytes,4,opt,name=first_message_timeout,proto3" json:"first_message_timeout,omitempty"`
	MaxConnsPerChannel  int32                  `protobuf:"varint,5,opt,name=max_conns_per_channel,proto3" json:"max_conns_per_channel,omitempty"`
	FailoverMaxSwitches int32                  `protobuf:"varint,6,opt,name=failover_max_switches,proto3" json:"failover_max_switches,omitempty"`
	StickyTtl           string                 `protobuf:"bytes,7,opt,name=sticky_ttl,proto3" json:"sticky_ttl,omitempty"`
	DrainTimeout        string                 `protobuf:"bytes,8,opt,name=drain_timeout,proto3" json:"drain_timeout,omitempty"`
	RedisAddr           string                 `protobuf:"bytes,9,opt,name=redis_addr,proto3" json:"redis_addr,omitempty"`
	RedisPassword       string                 `protobuf:"bytes,10,opt,name=redis_password,proto3" json:"redis_password,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenaiWS) Reset() {
	*x = OpenaiWS{}
	mi := &file_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenaiWS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenaiWS) ProtoMessage() {}

func (x *OpenaiWS) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenaiWS.ProtoReflect.Descriptor instead.
func (*OpenaiWS) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{14}
}

func (x *OpenaiWS) GetWriteTimeout() string {
	if x != nil {
		return x.WriteTimeout
	}
	return ""
}

func (x *OpenaiWS) GetIdleTimeout() string {
	if x != nil {
		return x.IdleTimeout
	}
	return ""
}

func (x *OpenaiWS) GetDialTimeout() string {
	if x != nil {
		return x.DialTimeout
	}
	return ""
}

func (x *OpenaiWS) GetFirstMessageTimeout() string {
	if x != nil {
		return x.FirstMessageTimeout
	}
	return ""
}

func (x *OpenaiWS) GetMaxConnsPerChannel() int32 {
	if x != nil {
		return x.MaxConnsPerChannel
	}
	return 0
}

func (x *OpenaiWS) GetFailoverMaxSwitches() int32 {
	if x != nil {
		return x.FailoverMaxSwitches
	}
	return 0
}

func (x *OpenaiWS) GetStickyTtl() string {
	if x != nil {
		return x.StickyTtl
	}
	return ""
}

func (x *OpenaiWS) GetDrainTimeout() string {
	if x != nil {
		return x.DrainTimeout
	}
	return ""
}

func (x *OpenaiWS) GetRedisAddr() string {
	if x != nil {
		return x.RedisAddr
	}
	return ""
}

func (x *OpenaiWS) GetRedisPassword() string {
	if x != nil {
		return x.RedisPassword
	}
	return ""
}

// HybridAdaptorConfig controls the hybrid adaptor layer.
type HybridAdaptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IdentityTtl      string                 `protobuf:"bytes,2,opt,name=identity_ttl,proto3" json:"identity_ttl,omitempty"`
	RefreshInterval  string                 `protobuf:"bytes,3,opt,name=refresh_interval,proto3" json:"refresh_interval,omitempty"`
	RefreshLookahead string                 `protobuf:"bytes,4,opt,name=refresh_lookahead,proto3" json:"refresh_lookahead,omitempty"`
	TokenRefresh     *TokenRefresh          `protobuf:"bytes,5,opt,name=token_refresh,proto3" json:"token_refresh,omitempty"`
	RuntimeBlock     *RuntimeBlock          `protobuf:"bytes,6,opt,name=runtime_block,proto3" json:"runtime_block,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HybridAdaptor) Reset() {
	*x = HybridAdaptor{}
	mi := &file_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridAdaptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridAdaptor) ProtoMessage() {}

func (x *HybridAdaptor) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridAdaptor.ProtoReflect.Descriptor instead.
func (*HybridAdaptor) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{15}
}

func (x *HybridAdaptor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HybridAdaptor) GetIdentityTtl() string {
	if x != nil {
		return x.IdentityTtl
	}
	return ""
}

func (x *HybridAdaptor) GetRefreshInterval() string {
	if x != nil {
		return x.RefreshInterval
	}
	return ""
}

func (x *HybridAdaptor) GetRefreshLookahead() string {
	if x != nil {
		return x.RefreshLookahead
	}
	return ""
}

func (x *HybridAdaptor) GetTokenRefresh() *TokenRefresh {
	if x != nil {
		return x.TokenRefresh
	}
	return nil
}

func (x *HybridAdaptor) GetRuntimeBlock() *RuntimeBlock {
	if x != nil {
		return x.RuntimeBlock
	}
	return nil
}

type TokenRefresh struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Enabled                  bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CheckIntervalMinutes     int32                  `protobuf:"varint,2,opt,name=check_interval_minutes,proto3" json:"check_interval_minutes,omitempty"`
	RefreshBeforeExpiryHours int32                  `protobuf:"varint,3,opt,name=refresh_before_expiry_hours,proto3" json:"refresh_before_expiry_hours,omitempty"`
	MaxRetries               int32                  `protobuf:"varint,4,opt,name=max_retries,proto3" json:"max_retries,omitempty"`
	RetryBackoffSeconds      int32                  `protobuf:"varint,5,opt,name=retry_backoff_seconds,proto3" json:"retry_backoff_seconds,omitempty"`
	TempUnschedDuration      string                 `protobuf:"bytes,6,opt,name=temp_unsched_duration,proto3" json:"temp_unsched_duration,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TokenRefresh) Reset() {
	*x = TokenRefresh{}
	mi := &file_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefresh) ProtoMessage() {}

func (x *TokenRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefresh.ProtoReflect.Descriptor instead.
func (*TokenRefresh) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{16}
}

func (x *TokenRefresh) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TokenRefresh) GetCheckIntervalMinutes() int32 {
	if x != nil {
		return x.CheckIntervalMinutes
	}
	return 0
}

func (x *TokenRefresh) GetRefreshBeforeExpiryHours() int32 {
	if x != nil {
		return x.RefreshBeforeExpiryHours
	}
	return 0
}

func (x *TokenRefresh) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TokenRefresh) GetRetryBackoffSeconds() int32 {
	if x != nil {
		return x.RetryBackoffSeconds
	}
	return 0
}

func (x *TokenRefresh) GetTempUnschedDuration() string {
	if x != nil {
		return x.TempUnschedDuration
	}
	return ""
}

type RuntimeBlock struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RateLimitedDuration  string                 `protobuf:"bytes,1,opt,name=rate_limited_duration,proto3" json:"rate_limited_duration,omitempty"`
	UnauthorizedDuration string                 `protobuf:"bytes,2,opt,name=unauthorized_duration,proto3" json:"unauthorized_duration,omitempty"`
	ServerErrorDuration  string                 `protobuf:"bytes,3,opt,name=server_error_duration,proto3" json:"server_error_duration,omitempty"`
	OverloadedDuration   string                 `protobuf:"bytes,4,opt,name=overloaded_duration,proto3" json:"overloaded_duration,omitempty"`
	ActiveGaugeInterval  string                 `protobuf:"bytes,5,opt,name=active_gauge_interval,proto3" json:"active_gauge_interval,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RuntimeBlock) Reset() {
	*x = RuntimeBlock{}
	mi := &file_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeBlock) ProtoMessage() {}

func (x *RuntimeBlock) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeBlock.ProtoReflect.Descriptor instead.
func (*RuntimeBlock) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeBlock) GetRateLimitedDuration() string {
	if x != nil {
		return x.RateLimitedDuration
	}
	return ""
}

func (x *RuntimeBlock) GetUnauthorizedDuration() string {
	if x != nil {
		return x.UnauthorizedDuration
	}
	return ""
}

func (x *RuntimeBlock) GetServerErrorDuration() string {
	if x != nil {
		return x.ServerErrorDuration
	}
	return ""
}

func (x *RuntimeBlock) GetOverloadedDuration() string {
	if x != nil {
		return x.OverloadedDuration
	}
	return ""
}

func (x *RuntimeBlock) GetActiveGaugeInterval() string {
	if x != nil {
		return x.ActiveGaugeInterval
	}
	return ""
}

// SessionStickyConfig gates cross-session subscription-account stickiness.
type SessionSticky struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSticky) Reset() {
	*x = SessionSticky{}
	mi := &file_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSticky) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSticky) ProtoMessage() {}

func (x *SessionSticky) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSticky.ProtoReflect.Descriptor instead.
func (*SessionSticky) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{18}
}

func (x *SessionSticky) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SubscriptionConfig controls user subscription quota enforcement.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UserRpmLimit  int32                  `protobuf:"varint,2,opt,name=user_rpm_limit,proto3" json:"user_rpm_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{19}
}

func (x *Subscription) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Subscription) GetUserRpmLimit() int32 {
	if x != nil {
		return x.UserRpmLimit
	}
	return 0
}

// RelayOrchestratorConfig controls the handler -> orchestrator -> forwarder route.
type RelayOrchestrator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayOrchestrator) Reset() {
	*x = RelayOrchestrator{}
	mi := &file_conf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOrchestrator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOrchestrator) ProtoMessage() {}

func (x *RelayOrchestrator) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOrchestrator.ProtoReflect.Descriptor instead.
func (*RelayOrchestrator) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{20}
}

func (x *RelayOrchestrator) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ChannelCacheConfig controls the multi-level ChannelCache.
type ChannelCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCache) Reset() {
	*x = ChannelCache{}
	mi := &file_conf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCache) ProtoMessage() {}

func (x *ChannelCache) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCache.ProtoReflect.Descriptor instead.
func (*ChannelCache) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{21}
}

func (x *ChannelCache) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// IdempotencyConfig controls idempotency middleware.
type Idempotency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Ttl           string                 `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idempotency) Reset() {
	*x = Idempotency{}
	mi := &file_conf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idempotency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idempotency) ProtoMessage() {}

func (x *Idempotency) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idempotency.ProtoReflect.Descriptor instead.
func (*Idempotency) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{22}
}

func (x *Idempotency) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Idempotency) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

// AuditConfig controls audit logging.
type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_conf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{23}
}

func (x *Audit) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ResilienceConfig controls resilience features.
type Resilience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resilience) Reset() {
	*x = Resilience{}
	mi := &file_conf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resilience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resilience) ProtoMessage() {}

func (x *Resilience) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resilience.ProtoReflect.Descriptor instead.
func (*Resilience) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{24}
}

func (x *Resilience) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Resilience) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// MtlsConfig controls mTLS configuration.
type Mtls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CertFile      string                 `protobuf:"bytes,2,opt,name=cert_file,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,3,opt,name=key_file,proto3" json:"key_file,omitempty"`
	CaFile        string                 `protobuf:"bytes,4,opt,name=ca_file,proto3" json:"ca_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mtls) Reset() {
	*x = Mtls{}
	mi := &file_conf_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mtls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mtls) ProtoMessage() {}

func (x *Mtls) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mtls.ProtoReflect.Descriptor instead.
func (*Mtls) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{25}
}

func (x *Mtls) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Mtls) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Mtls) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Mtls) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\fapi.relay.v1\"\xfa\x06\n" +
	"\tBootstrap\x12,\n" +
	"\x06server\x18\x01 \x01(\v2\x14.api.relay.v1.ServerR\x06server\x12/\n" +
	"\aclients\x18\x02 \x01(\v2\x15.api.relay.v1.ClientsR\aclients\x12)\n" +
	"\x05retry\x18\x03 \x01(\v2\x13.api.relay.v1.RetryR\x05retry\x12,\n" +
	"\x06models\x18\x04 \x01(\v2\x14.api.relay.v1.ModelsR\x06models\x122\n" +
	"\bregistry\x18\x05 \x01(\v2\x16.api.relay.v1.RegistryR\bregistry\x12)\n" +
	"\x05redis\x18\x06 \x01(\v2\x13.api.relay.v1.RedisR\x05redis\x123\n" +
	"\topenai_ws\x18\a \x01(\v2\x16.api.relay.v1.OpenaiWSR\bopenaiWs\x12B\n" +
	"\x0ehybrid_adaptor\x18\b \x01(\v2\x1b.api.relay.v1.HybridAdaptorR\rhybridAdaptor\x12B\n" +
	"\x0esession_sticky\x18\t \x01(\v2\x1b.api.relay.v1.SessionStickyR\rsessionSticky\x12>\n" +
	"\fsubscription\x18\n" +
	" \x01(\v2\x1a.api.relay.v1.SubscriptionR\fsubscription\x12N\n" +
	"\x12relay_orchestrator\x18\v \x01(\v2\x1f.api.relay.v1.RelayOrchestratorR\x11relayOrchestrator\x12?\n" +
	"\rchannel_cache\x18\f \x01(\v2\x1a.api.relay.v1.ChannelCacheR\fchannelCache\x12;\n" +
	"\vidempotency\x18\r \x01(\v2\x19.api.relay.v1.IdempotencyR\vidempotency\x12)\n" +
	"\x05audit\x18\x0e \x01(\v2\x13.api.relay.v1.AuditR\x05audit\x128\n" +
	"\n" +
	"resilience\x18\x0f \x01(\v2\x18.api.relay.v1.ResilienceR\n" +
	"resilience\x12&\n" +
	"\x04mtls\x18\x10 \x01(\v2\x12.api.relay.v1.MtlsR\x04mtls\"X\n" +
	"\x06Server\x12&\n" +
	"\x04http\x18\x01 \x01(\v2\x12.api.relay.v1.HTTPR\x04http\x12&\n" +
	"\x04grpc\x18\x02 \x01(\v2\x12.api.relay.v1.GRPCR\x04grpc\"\x1a\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\x1a\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xc4\x01\n" +
	"\aClients\x122\n" +
	"\bidentity\x18\x01 \x01(\v2\x16.api.relay.v1.IdentityR\bidentity\x12/\n" +
	"\achannel\x18\x02 \x01(\v2\x15.api.relay.v1.ChannelR\achannel\x12/\n" +
	"\abilling\x18\x03 \x01(\v2\x15.api.relay.v1.BillingR\abilling\x12#\n" +
	"\x03log\x18\x04 \x01(\v2\x11.api.relay.v1.LogR\x03log\"&\n" +
	"\bIdentity\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"%\n" +
	"\aChannel\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"%\n" +
	"\aBilling\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"!\n" +
	"\x03Log\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"\xc7\x01\n" +
	"\x05Retry\x12\"\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\fmax_attempts\x12*\n" +
	"\x10initial_interval\x18\x02 \x01(\tR\x10initial_interval\x12\"\n" +
	"\fmax_interval\x18\x03 \x01(\tR\fmax_interval\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x01R\n" +
	"multiplier\x12*\n" +
	"\x10retryable_status\x18\x05 \x03(\x05R\x10retryable_status\"\x1c\n" +
	"\x06Models\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"7\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xcb\x01\n" +
	"\bRegistry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12,\n" +
	"\x06consul\x18\x02 \x01(\v2\x14.api.relay.v1.ConsulR\x06consul\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.api.relay.v1.Registry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x06Consul\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x124\n" +
	"\x15health_check_interval\x18\x02 \x01(\x03R\x15health_check_interval\"\xa8\x03\n" +
	"\bOpenaiWS\x12$\n" +
	"\rwrite_timeout\x18\x01 \x01(\tR\rwrite_timeout\x12\"\n" +
	"\fidle_timeout\x18\x02 \x01(\tR\fidle_timeout\x12\"\n" +
	"\fdial_timeout\x18\x03 \x01(\tR\fdial_timeout\x124\n" +
	"\x15first_message_timeout\x18\x04 \x01(\tR\x15first_message_timeout\x124\n" +
	"\x15max_conns_per_channel\x18\x05 \x01(\x05R\x15max_conns_per_channel\x124\n" +
	"\x15failover_max_switches\x18\x06 \x01(\x05R\x15failover_max_switches\x12\x1e\n" +
	"\n" +
	"sticky_ttl\x18\a \x01(\tR\n" +
	"sticky_ttl\x12$\n" +
	"\rdrain_timeout\x18\b \x01(\tR\rdrain_timeout\x12\x1e\n" +
	"\n" +
	"redis_addr\x18\t \x01(\tR\n" +
	"redis_addr\x12&\n" +
	"\x0eredis_password\x18\n" +
	" \x01(\tR\x0eredis_password\"\xab\x02\n" +
	"\rHybridAdaptor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\"\n" +
	"\fidentity_ttl\x18\x02 \x01(\tR\fidentity_ttl\x12*\n" +
	"\x10refresh_interval\x18\x03 \x01(\tR\x10refresh_interval\x12,\n" +
	"\x11refresh_lookahead\x18\x04 \x01(\tR\x11refresh_lookahead\x12@\n" +
	"\rtoken_refresh\x18\x05 \x01(\v2\x1a.api.relay.v1.TokenRefreshR\rtoken_refresh\x12@\n" +
	"\rruntime_block\x18\x06 \x01(\v2\x1a.api.relay.v1.RuntimeBlockR\rruntime_block\"\xb0\x02\n" +
	"\fTokenRefresh\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x126\n" +
	"\x16check_interval_minutes\x18\x02 \x01(\x05R\x16check_interval_minutes\x12@\n" +
	"\x1brefresh_before_expiry_hours\x18\x03 \x01(\x05R\x1brefresh_before_expiry_hours\x12 \n" +
	"\vmax_retries\x18\x04 \x01(\x05R\vmax_retries\x124\n" +
	"\x15retry_backoff_seconds\x18\x05 \x01(\x05R\x15retry_backoff_seconds\x124\n" +
	"\x15temp_unsched_duration\x18\x06 \x01(\tR\x15temp_unsched_duration\"\x98\x02\n" +
	"\fRuntimeBlock\x124\n" +
	"\x15rate_limited_duration\x18\x01 \x01(\tR\x15rate_limited_duration\x124\n" +
	"\x15unauthorized_duration\x18\x02 \x01(\tR\x15unauthorized_duration\x124\n" +
	"\x15server_error_duration\x18\x03 \x01(\tR\x15server_error_duration\x120\n" +
	"\x13overloaded_duration\x18\x04 \x01(\tR\x13overloaded_duration\x124\n" +
	"\x15active_gauge_interval\x18\x05 \x01(\tR\x15active_gauge_interval\")\n" +
	"\rSessionSticky\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"P\n" +
	"\fSubscription\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12&\n" +
	"\x0euser_rpm_limit\x18\x02 \x01(\x05R\x0euser_rpm_limit\"-\n" +
	"\x11RelayOrchestrator\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"(\n" +
	"\fChannelCache\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"9\n" +
	"\vIdempotency\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\tR\x03ttl\"!\n" +
	"\x05Audit\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"@\n" +
	"\n" +
	"Resilience\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"t\n" +
	"\x04Mtls\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\tcert_file\x18\x02 \x01(\tR\tcert_file\x12\x1a\n" +
	"\bkey_file\x18\x03 \x01(\tR\bkey_file\x12\x18\n" +
	"\aca_file\x18\x04 \x01(\tR\aca_fileB\"Z micro-one-api/internal/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),         // 0: api.relay.v1.Bootstrap
	(*Server)(nil),            // 1: api.relay.v1.Server
	(*HTTP)(nil),              // 2: api.relay.v1.HTTP
	(*GRPC)(nil),              // 3: api.relay.v1.GRPC
	(*Clients)(nil),           // 4: api.relay.v1.Clients
	(*Identity)(nil),          // 5: api.relay.v1.Identity
	(*Channel)(nil),           // 6: api.relay.v1.Channel
	(*Billing)(nil),           // 7: api.relay.v1.Billing
	(*Log)(nil),               // 8: api.relay.v1.Log
	(*Retry)(nil),             // 9: api.relay.v1.Retry
	(*Models)(nil),            // 10: api.relay.v1.Models
	(*Redis)(nil),             // 11: api.relay.v1.Redis
	(*Registry)(nil),          // 12: api.relay.v1.Registry
	(*Consul)(nil),            // 13: api.relay.v1.Consul
	(*OpenaiWS)(nil),          // 14: api.relay.v1.OpenaiWS
	(*HybridAdaptor)(nil),     // 15: api.relay.v1.HybridAdaptor
	(*TokenRefresh)(nil),      // 16: api.relay.v1.TokenRefresh
	(*RuntimeBlock)(nil),      // 17: api.relay.v1.RuntimeBlock
	(*SessionSticky)(nil),     // 18: api.relay.v1.SessionSticky
	(*Subscription)(nil),      // 19: api.relay.v1.Subscription
	(*RelayOrchestrator)(nil), // 20: api.relay.v1.RelayOrchestrator
	(*ChannelCache)(nil),      // 21: api.relay.v1.ChannelCache
	(*Idempotency)(nil),       // 22: api.relay.v1.Idempotency
	(*Audit)(nil),             // 23: api.relay.v1.Audit
	(*Resilience)(nil),        // 24: api.relay.v1.Resilience
	(*Mtls)(nil),              // 25: api.relay.v1.Mtls
	nil,                       // 26: api.relay.v1.Registry.MetadataEntry
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: api.relay.v1.Bootstrap.server:type_name -> api.relay.v1.Server
	4,  // 1: api.relay.v1.Bootstrap.clients:type_name -> api.relay.v1.Clients
	9,  // 2: api.relay.v1.Bootstrap.retry:type_name -> api.relay.v1.Retry
	10, // 3: api.relay.v1.Bootstrap.models:type_name -> api.relay.v1.Models
	12, // 4: api.relay.v1.Bootstrap.registry:type_name -> api.relay.v1.Registry
	11, // 5: api.relay.v1.Bootstrap.redis:type_name -> api.relay.v1.Redis
	14, // 6: api.relay.v1.Bootstrap.openai_ws:type_name -> api.relay.v1.OpenaiWS
	15, // 7: api.relay.v1.Bootstrap.hybrid_adaptor:type_name -> api.relay.v1.HybridAdaptor
	18, // 8: api.relay.v1.Bootstrap.session_sticky:type_name -> api.relay.v1.SessionSticky
	19, // 9: api.relay.v1.Bootstrap.subscription:type_name -> api.relay.v1.Subscription
	20, // 10: api.relay.v1.Bootstrap.relay_orchestrator:type_name -> api.relay.v1.RelayOrchestrator
	21, // 11: api.relay.v1.Bootstrap.channel_cache:type_name -> api.relay.v1.ChannelCache
	22, // 12: api.relay.v1.Bootstrap.idempotency:type_name -> api.relay.v1.Idempotency
	23, // 13: api.relay.v1.Bootstrap.audit:type_name -> api.relay.v1.Audit
	24, // 14: api.relay.v1.Bootstrap.resilience:type_name -> api.relay.v1.Resilience
	25, // 15: api.relay.v1.Bootstrap.mtls:type_name -> api.relay.v1.Mtls
	2,  // 16: api.relay.v1.Server.http:type_name -> api.relay.v1.HTTP
	3,  // 17: api.relay.v1.Server.grpc:type_name -> api.relay.v1.GRPC
	5,  // 18: api.relay.v1.Clients.identity:type_name -> api.relay.v1.Identity
	6,  // 19: api.relay.v1.Clients.channel:type_name -> api.relay.v1.Channel
	7,  // 20: api.relay.v1.Clients.billing:type_name -> api.relay.v1.Billing
	8,  // 21: api.relay.v1.Clients.log:type_name -> api.relay.v1.Log
	13, // 22: api.relay.v1.Registry.consul:type_name -> api.relay.v1.Consul
	26, // 23: api.relay.v1.Registry.metadata:type_name -> api.relay.v1.Registry.MetadataEntry
	16, // 24: api.relay.v1.HybridAdaptor.token_refresh:type_name -> api.relay.v1.TokenRefresh
	17, // 25: api.relay.v1.HybridAdaptor.runtime_block:type_name -> api.relay.v1.RuntimeBlock
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
