server:
  http:
    addr: 0.0.0.0:8000
  grpc:
    addr: 0.0.0.0:9000
registry:
  type: ${REGISTRY_TYPE:-}
  consul:
    address: ${CONSUL_ADDR:-127.0.0.1:8500}
    health_check_interval: 10
clients:
  identity:
    endpoint: 127.0.0.1:9001
  channel:
    endpoint: 127.0.0.1:9002
  billing:
    endpoint: 127.0.0.1:9004
data:
  database:
    driver: mysql
    source: ${DATABASE_DSN:-root:password@tcp(127.0.0.1:3306)/oneapi}

