// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"micro-one-api/app/monitor/internal/biz"
	"micro-one-api/app/monitor/internal/conf"
	"micro-one-api/app/monitor/internal/data"
	"micro-one-api/app/monitor/internal/server"
	"micro-one-api/app/monitor/internal/service"
	registry2 "micro-one-api/platform/registry"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/registry"
	"github.com/google/wire"

	_ "github.com/go-kratos/kratos/v2/config/file"
)

// Injectors from wire.go:

func InitApp(confPath string) (*kratos.App, func(), error) {
	config, err := loadConfig(confPath)
	if err != nil {
		return nil, nil, err
	}
	repository, err := newRepo(config)
	if err != nil {
		return nil, nil, err
	}
	monitorUsecase := biz.NewMonitorUsecase(repository)
	monitorService := service.NewMonitorService(monitorUsecase)
	mainRegistrarResult := provideRegistrar(config)
	app, cleanup := newApp(config, monitorService, mainRegistrarResult)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	newRepo, biz.NewMonitorUsecase, service.NewMonitorService, server.NewGRPCServer, server.NewHTTPServer, provideRegistrar, wire.Bind(new(biz.MonitorRepo), new(*data.Repository)),
)

func newRepo(cfg *conf.Config) (*data.Repository, error) {
	return data.NewRepositoryFromEnv(cfg.Data.Database.Driver, cfg.Data.Database.Source, cfg.Data.Database.Schema)
}

type registrarResult struct {
	Registrar registry.Registrar
}

func provideRegistrar(cfg *conf.Config) registrarResult {
	registrar, err := registry2.NewRegistrar(cfg.Registry)
	if err != nil {
		return registrarResult{}
	}
	return registrarResult{Registrar: registrar}
}

func newApp(cfg *conf.Config, svc *service.MonitorService, reg registrarResult) (*kratos.App, func()) {
	grpcSrv := server.NewGRPCServer(cfg.Server.GRPC.Addr, svc)
	httpSrv := server.NewHTTPServer(cfg.Server.HTTP.Addr, svc)
	_, channelCleanup := newChannelHealthChecker(cfg)
	opts := []kratos.Option{kratos.Name("monitor-worker"), kratos.Server(grpcSrv, httpSrv)}
	if reg.Registrar != nil {
		opts = append(opts, kratos.Registrar(reg.Registrar))
	}
	app := kratos.New(opts...)
	return app, func() {
		if channelCleanup != nil {
			channelCleanup()
		}
	}
}

func newChannelHealthChecker(cfg *conf.Config) (*biz.ChannelHealthChecker, func()) {
	return newChannelHealthCheckerImpl(cfg)
}
