// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Quota         int64                  `protobuf:"varint,7,opt,name=quota,proto3" json:"quota,omitempty"`
	UsedQuota     int64                  `protobuf:"varint,8,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	FrozenQuota   int64                  `protobuf:"varint,9,opt,name=frozen_quota,json=frozenQuota,proto3" json:"frozen_quota,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLoginAt   int64                  `protobuf:"varint,11,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *UserInfo) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *UserInfo) GetFrozenQuota() int64 {
	if x != nil {
		return x.FrozenQuota
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

type ChannelSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type               int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Group              string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Status             int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Priority           int64                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Models             string                 `protobuf:"bytes,8,opt,name=models,proto3" json:"models,omitempty"`
	Weight             uint32                 `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	TestTime           int64                  `protobuf:"varint,10,opt,name=test_time,json=testTime,proto3" json:"test_time,omitempty"`
	ResponseTime       int64                  `protobuf:"varint,11,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Balance            float64                `protobuf:"fixed64,12,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceUpdatedTime int64                  `protobuf:"varint,13,opt,name=balance_updated_time,json=balanceUpdatedTime,proto3" json:"balance_updated_time,omitempty"`
	UsedQuota          int64                  `protobuf:"varint,14,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelSummary) Reset() {
	*x = ChannelSummary{}
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSummary) ProtoMessage() {}

func (x *ChannelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSummary.ProtoReflect.Descriptor instead.
func (*ChannelSummary) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelSummary) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChannelSummary) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChannelSummary) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelSummary) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChannelSummary) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *ChannelSummary) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ChannelSummary) GetTestTime() int64 {
	if x != nil {
		return x.TestTime
	}
	return 0
}

func (x *ChannelSummary) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *ChannelSummary) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ChannelSummary) GetBalanceUpdatedTime() int64 {
	if x != nil {
		return x.BalanceUpdatedTime
	}
	return 0
}

func (x *ChannelSummary) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

type ChannelConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion        string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Region            string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	LibraryId         string                 `protobuf:"bytes,3,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	Plugin            string                 `protobuf:"bytes,4,opt,name=plugin,proto3" json:"plugin,omitempty"`
	VertexAiProjectId string                 `protobuf:"bytes,5,opt,name=vertex_ai_project_id,json=vertexAiProjectId,proto3" json:"vertex_ai_project_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_api_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelConfig) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ChannelConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ChannelConfig) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *ChannelConfig) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ChannelConfig) GetVertexAiProjectId() string {
	if x != nil {
		return x.VertexAiProjectId
	}
	return ""
}

type ChannelInfo struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	Id                                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                              int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status                            int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	BaseUrl                           string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Group                             string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Models                            string                 `protobuf:"bytes,7,opt,name=models,proto3" json:"models,omitempty"`
	Priority                          int64                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Key                               string                 `protobuf:"bytes,9,opt,name=key,proto3" json:"key,omitempty"`
	Config                            *ChannelConfig         `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	Weight                            uint32                 `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	TestTime                          int64                  `protobuf:"varint,12,opt,name=test_time,json=testTime,proto3" json:"test_time,omitempty"`
	ResponseTime                      int64                  `protobuf:"varint,13,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Balance                           float64                `protobuf:"fixed64,14,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceUpdatedTime                int64                  `protobuf:"varint,15,opt,name=balance_updated_time,json=balanceUpdatedTime,proto3" json:"balance_updated_time,omitempty"`
	UsedQuota                         int64                  `protobuf:"varint,16,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	ModelMapping                      string                 `protobuf:"bytes,17,opt,name=model_mapping,json=modelMapping,proto3" json:"model_mapping,omitempty"`
	SystemPrompt                      string                 `protobuf:"bytes,18,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	BalanceRefreshLastError           string                 `protobuf:"bytes,19,opt,name=balance_refresh_last_error,json=balanceRefreshLastError,proto3" json:"balance_refresh_last_error,omitempty"`
	BalanceRefreshLastSuccessTime     int64                  `protobuf:"varint,20,opt,name=balance_refresh_last_success_time,json=balanceRefreshLastSuccessTime,proto3" json:"balance_refresh_last_success_time,omitempty"`
	ConsecutiveBalanceRefreshFailures int32                  `protobuf:"varint,21,opt,name=consecutive_balance_refresh_failures,json=consecutiveBalanceRefreshFailures,proto3" json:"consecutive_balance_refresh_failures,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_api_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelInfo) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ChannelInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChannelInfo) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *ChannelInfo) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChannelInfo) GetConfig() *ChannelConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChannelInfo) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ChannelInfo) GetTestTime() int64 {
	if x != nil {
		return x.TestTime
	}
	return 0
}

func (x *ChannelInfo) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *ChannelInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ChannelInfo) GetBalanceUpdatedTime() int64 {
	if x != nil {
		return x.BalanceUpdatedTime
	}
	return 0
}

func (x *ChannelInfo) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *ChannelInfo) GetModelMapping() string {
	if x != nil {
		return x.ModelMapping
	}
	return ""
}

func (x *ChannelInfo) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChannelInfo) GetBalanceRefreshLastError() string {
	if x != nil {
		return x.BalanceRefreshLastError
	}
	return ""
}

func (x *ChannelInfo) GetBalanceRefreshLastSuccessTime() int64 {
	if x != nil {
		return x.BalanceRefreshLastSuccessTime
	}
	return 0
}

func (x *ChannelInfo) GetConsecutiveBalanceRefreshFailures() int32 {
	if x != nil {
		return x.ConsecutiveBalanceRefreshFailures
	}
	return 0
}

type AccountSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quota         int64                  `protobuf:"varint,2,opt,name=quota,proto3" json:"quota,omitempty"`
	UsedQuota     int64                  `protobuf:"varint,3,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	RequestCount  int64                  `protobuf:"varint,4,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	GroupRatio    float64                `protobuf:"fixed64,6,opt,name=group_ratio,json=groupRatio,proto3" json:"group_ratio,omitempty"`
	FrozenQuota   int64                  `protobuf:"varint,7,opt,name=frozen_quota,json=frozenQuota,proto3" json:"frozen_quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSnapshot) Reset() {
	*x = AccountSnapshot{}
	mi := &file_api_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSnapshot) ProtoMessage() {}

func (x *AccountSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSnapshot.ProtoReflect.Descriptor instead.
func (*AccountSnapshot) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *AccountSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountSnapshot) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *AccountSnapshot) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *AccountSnapshot) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *AccountSnapshot) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AccountSnapshot) GetGroupRatio() float64 {
	if x != nil {
		return x.GroupRatio
	}
	return 0
}

func (x *AccountSnapshot) GetFrozenQuota() int64 {
	if x != nil {
		return x.FrozenQuota
	}
	return 0
}

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Quota         int64                  `protobuf:"varint,5,opt,name=quota,proto3" json:"quota,omitempty"`
	UsedQuota     int64                  `protobuf:"varint,6,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	RequestCount  int64                  `protobuf:"varint,7,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	FrozenQuota   int64                  `protobuf:"varint,8,opt,name=frozen_quota,json=frozenQuota,proto3" json:"frozen_quota,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_api_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *AccountInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AccountInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AccountInfo) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *AccountInfo) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *AccountInfo) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *AccountInfo) GetFrozenQuota() int64 {
	if x != nil {
		return x.FrozenQuota
	}
	return 0
}

func (x *AccountInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RedeemCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCode) Reset() {
	*x = RedeemCode{}
	mi := &file_api_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCode) ProtoMessage() {}

func (x *RedeemCode) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCode.ProtoReflect.Descriptor instead.
func (*RedeemCode) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *RedeemCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RedeemCode) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RedeemCode) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RedeemCode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RedeemCode) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RedeemCode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RedeemCode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RedeemCodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCodeInfo) Reset() {
	*x = RedeemCodeInfo{}
	mi := &file_api_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCodeInfo) ProtoMessage() {}

func (x *RedeemCodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCodeInfo.ProtoReflect.Descriptor instead.
func (*RedeemCodeInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *RedeemCodeInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemCodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RedeemCodeInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RedeemCodeInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RedeemCodeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RedeemCodeInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RedeemCodeInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_api_common_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *LedgerEntry) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LedgerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerInfo) Reset() {
	*x = LedgerInfo{}
	mi := &file_api_common_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerInfo) ProtoMessage() {}

func (x *LedgerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerInfo.ProtoReflect.Descriptor instead.
func (*LedgerInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *LedgerInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LedgerInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerInfo) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *LedgerInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerInfo) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *LedgerInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *LedgerInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SystemOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SiteTitle           string                 `protobuf:"bytes,1,opt,name=site_title,json=siteTitle,proto3" json:"site_title,omitempty"`
	SiteDescription     string                 `protobuf:"bytes,2,opt,name=site_description,json=siteDescription,proto3" json:"site_description,omitempty"`
	RegistrationEnabled bool                   `protobuf:"varint,3,opt,name=registration_enabled,json=registrationEnabled,proto3" json:"registration_enabled,omitempty"`
	ChatHistoryEnabled  bool                   `protobuf:"varint,4,opt,name=chat_history_enabled,json=chatHistoryEnabled,proto3" json:"chat_history_enabled,omitempty"`
	Theme               string                 `protobuf:"bytes,5,opt,name=theme,proto3" json:"theme,omitempty"`
	Notice              string                 `protobuf:"bytes,6,opt,name=notice,proto3" json:"notice,omitempty"`
	MaxTokenPerUser     int64                  `protobuf:"varint,7,opt,name=max_token_per_user,json=maxTokenPerUser,proto3" json:"max_token_per_user,omitempty"`
	DefaultRatio        float64                `protobuf:"fixed64,8,opt,name=default_ratio,json=defaultRatio,proto3" json:"default_ratio,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemOptions) Reset() {
	*x = SystemOptions{}
	mi := &file_api_common_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemOptions) ProtoMessage() {}

func (x *SystemOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemOptions.ProtoReflect.Descriptor instead.
func (*SystemOptions) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *SystemOptions) GetSiteTitle() string {
	if x != nil {
		return x.SiteTitle
	}
	return ""
}

func (x *SystemOptions) GetSiteDescription() string {
	if x != nil {
		return x.SiteDescription
	}
	return ""
}

func (x *SystemOptions) GetRegistrationEnabled() bool {
	if x != nil {
		return x.RegistrationEnabled
	}
	return false
}

func (x *SystemOptions) GetChatHistoryEnabled() bool {
	if x != nil {
		return x.ChatHistoryEnabled
	}
	return false
}

func (x *SystemOptions) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *SystemOptions) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *SystemOptions) GetMaxTokenPerUser() int64 {
	if x != nil {
		return x.MaxTokenPerUser
	}
	return 0
}

func (x *SystemOptions) GetDefaultRatio() float64 {
	if x != nil {
		return x.DefaultRatio
	}
	return 0
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_api_common_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_api_common_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *PaginationResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_common_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{13}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_common_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_common_v1_common_proto protoreflect.FileDescriptor

const file_api_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/common.proto\x12\rapi.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x14\n" +
	"\x05quota\x18\a \x01(\x03R\x05quota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\b \x01(\x03R\tusedQuota\x12!\n" +
	"\ffrozen_quota\x18\t \x01(\x03R\vfrozenQuota\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\"\n" +
	"\rlast_login_at\x18\v \x01(\x03R\vlastLoginAt\"\x8e\x03\n" +
	"\x0eChannelSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x03R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06models\x18\b \x01(\tR\x06models\x12\x16\n" +
	"\x06weight\x18\t \x01(\rR\x06weight\x12\x1b\n" +
	"\ttest_time\x18\n" +
	" \x01(\x03R\btestTime\x12#\n" +
	"\rresponse_time\x18\v \x01(\x03R\fresponseTime\x12\x18\n" +
	"\abalance\x18\f \x01(\x01R\abalance\x120\n" +
	"\x14balance_updated_time\x18\r \x01(\x03R\x12balanceUpdatedTime\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x0e \x01(\x03R\tusedQuota\"\xb0\x01\n" +
	"\rChannelConfig\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"library_id\x18\x03 \x01(\tR\tlibraryId\x12\x16\n" +
	"\x06plugin\x18\x04 \x01(\tR\x06plugin\x12/\n" +
	"\x14vertex_ai_project_id\x18\x05 \x01(\tR\x11vertexAiProjectId\"\xf1\x05\n" +
	"\vChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x16\n" +
	"\x06models\x18\a \x01(\tR\x06models\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x03R\bpriority\x12\x10\n" +
	"\x03key\x18\t \x01(\tR\x03key\x124\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x1c.api.common.v1.ChannelConfigR\x06config\x12\x16\n" +
	"\x06weight\x18\v \x01(\rR\x06weight\x12\x1b\n" +
	"\ttest_time\x18\f \x01(\x03R\btestTime\x12#\n" +
	"\rresponse_time\x18\r \x01(\x03R\fresponseTime\x12\x18\n" +
	"\abalance\x18\x0e \x01(\x01R\abalance\x120\n" +
	"\x14balance_updated_time\x18\x0f \x01(\x03R\x12balanceUpdatedTime\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x10 \x01(\x03R\tusedQuota\x12#\n" +
	"\rmodel_mapping\x18\x11 \x01(\tR\fmodelMapping\x12#\n" +
	"\rsystem_prompt\x18\x12 \x01(\tR\fsystemPrompt\x12;\n" +
	"\x1abalance_refresh_last_error\x18\x13 \x01(\tR\x17balanceRefreshLastError\x12H\n" +
	"!balance_refresh_last_success_time\x18\x14 \x01(\x03R\x1dbalanceRefreshLastSuccessTime\x12O\n" +
	"$consecutive_balance_refresh_failures\x18\x15 \x01(\x05R!consecutiveBalanceRefreshFailures\"\xde\x01\n" +
	"\x0fAccountSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05quota\x18\x02 \x01(\x03R\x05quota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x03 \x01(\x03R\tusedQuota\x12#\n" +
	"\rrequest_count\x18\x04 \x01(\x03R\frequestCount\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x1f\n" +
	"\vgroup_ratio\x18\x06 \x01(\x01R\n" +
	"groupRatio\x12!\n" +
	"\ffrozen_quota\x18\a \x01(\x03R\vfrozenQuota\"\x90\x02\n" +
	"\vAccountInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x14\n" +
	"\x05quota\x18\x05 \x01(\x03R\x05quota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x06 \x01(\x03R\tusedQuota\x12#\n" +
	"\rrequest_count\x18\a \x01(\x03R\frequestCount\x12!\n" +
	"\ffrozen_quota\x18\b \x01(\x03R\vfrozenQuota\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\x8f\x02\n" +
	"\n" +
	"RedeemCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x01\n" +
	"\x0eRedeemCodeInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xfd\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe0\x01\n" +
	"\n" +
	"LedgerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xbe\x02\n" +
	"\rSystemOptions\x12\x1d\n" +
	"\n" +
	"site_title\x18\x01 \x01(\tR\tsiteTitle\x12)\n" +
	"\x10site_description\x18\x02 \x01(\tR\x0fsiteDescription\x121\n" +
	"\x14registration_enabled\x18\x03 \x01(\bR\x13registrationEnabled\x120\n" +
	"\x14chat_history_enabled\x18\x04 \x01(\bR\x12chatHistoryEnabled\x12\x14\n" +
	"\x05theme\x18\x05 \x01(\tR\x05theme\x12\x16\n" +
	"\x06notice\x18\x06 \x01(\tR\x06notice\x12+\n" +
	"\x12max_token_per_user\x18\a \x01(\x03R\x0fmaxTokenPerUser\x12#\n" +
	"\rdefault_ratio\x18\b \x01(\x01R\fdefaultRatio\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"*\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"\a\n" +
	"\x05Empty\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB&Z$micro-one-api/api/common/v1;commonv1b\x06proto3"

var (
	file_api_common_v1_common_proto_rawDescOnce sync.Once
	file_api_common_v1_common_proto_rawDescData []byte
)

func file_api_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)))
	})
	return file_api_common_v1_common_proto_rawDescData
}

var file_api_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_common_v1_common_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: api.common.v1.UserInfo
	(*ChannelSummary)(nil),        // 1: api.common.v1.ChannelSummary
	(*ChannelConfig)(nil),         // 2: api.common.v1.ChannelConfig
	(*ChannelInfo)(nil),           // 3: api.common.v1.ChannelInfo
	(*AccountSnapshot)(nil),       // 4: api.common.v1.AccountSnapshot
	(*AccountInfo)(nil),           // 5: api.common.v1.AccountInfo
	(*RedeemCode)(nil),            // 6: api.common.v1.RedeemCode
	(*RedeemCodeInfo)(nil),        // 7: api.common.v1.RedeemCodeInfo
	(*LedgerEntry)(nil),           // 8: api.common.v1.LedgerEntry
	(*LedgerInfo)(nil),            // 9: api.common.v1.LedgerInfo
	(*SystemOptions)(nil),         // 10: api.common.v1.SystemOptions
	(*PaginationRequest)(nil),     // 11: api.common.v1.PaginationRequest
	(*PaginationResponse)(nil),    // 12: api.common.v1.PaginationResponse
	(*Empty)(nil),                 // 13: api.common.v1.Empty
	(*Error)(nil),                 // 14: api.common.v1.Error
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_api_common_v1_common_proto_depIdxs = []int32{
	2,  // 0: api.common.v1.ChannelInfo.config:type_name -> api.common.v1.ChannelConfig
	15, // 1: api.common.v1.RedeemCode.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: api.common.v1.RedeemCode.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: api.common.v1.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_common_v1_common_proto_init() }
func file_api_common_v1_common_proto_init() {
	if File_api_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_common_v1_common_proto_depIdxs,
		MessageInfos:      file_api_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_common_v1_common_proto = out.File
	file_api_common_v1_common_proto_goTypes = nil
	file_api_common_v1_common_proto_depIdxs = nil
}
